
spring:
  application:
      name: zuulproxy

server:
  port: ${zuul.server.port:8083}

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${eureka.server.hostname:localhost}:${eureka.server.port:8081}/eureka
    register-with-eureka: true
    fetch-registry: true
  #instance:
    #prefer-ip-address: true



zuul:
  routes:
    app1:
      path: /client/*
      url: http://localhost:8085/client/
      strip-prefix: true
    





